env:
  browser: true
  es2021: true
extends:
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns: ['src/generated/**']
rules: { 'space-before-function-paren': 'off' }
