name: Publish npm package

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [ published ]

env:
  NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.15'

      - name: Authenticate Nodejs
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@open-ibc'

      - name: Build ibctl
        run: make build-ibctl

      - name: Publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          strategy: all
