name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate Docker
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    - name: Test
      run: make test-e2e

    - name: Show logs
      if: ${{ always() }}
      run: |
        date
        whoami
        docker ps -a
        ls -lR /tmp/ibctl-tests-* || true
        tail /tmp/ibctl-tests-*/run/*/* || true