name: Test

on:
  pull_request:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate Docker
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    - name: Build SDK
      run: make

    - name: Show logs
      if: ${{ always() }}
      run: |
        date
        docker ps -a
        tail /tmp/ibctl-tests-*/run/*/* || true