name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  TEST_IBCTL_WORKSPACE: /tmp/ibctl-e2e-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate Docker
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    - name: Test
      run: make test-all

    - name: Show logs
      if: ${{ always() }}
      run: |
        date
        whoami
        docker ps -a
        tail /tmp/*/run/*/* || true
